#
# Copyright (C) 2020-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

name: verify
on: 
  - pull_request

lint:
  runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
    with:
      path: neo
  - name: lint
    uses: ./.github/actions/neo-lint
jobs:
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
      with:
        path: neo
    - name: test
      working-directory: neo
      run: |
        nproc
        free
